In [12]:
using Zygote
using SparseArrays

In [9]:
gradient((a, b) -> a*b, 2, 3)

(3, 2)

In [10]:
W = rand(2, 3);
x = rand(3);

In [11]:
gradient(W -> sum(W * x), W)

([0.247144 0.508975 0.224706; 0.247144 0.508975 0.224706],)

In [40]:
W_sp = sprand(200, 300, 0.3);

In [32]:
W_sp

2×3 SparseMatrixCSC{Float64,Int64} with 1 stored entry:
  [2, 1]  =  0.738549

In [33]:
Matrix(W_sp)

2×3 Array{Float64,2}:
 0.0       0.0  0.0
 0.738549  0.0  0.0

In [41]:
x_sp = sprand(300, 0.3);

In [30]:
x_sp

3-element SparseVector{Float64,Int64} with 2 stored entries:
  [1]  =  0.93747
  [2]  =  0.892034

In [45]:
gradient(() -> sum(W * x_sp))

DimensionMismatch: DimensionMismatch("")

---

In [25]:
using Flux

┌ Info: CUDAdrv.jl failed to initialize, GPU functionality unavailable (set JULIA_CUDA_SILENT or JULIA_CUDA_VERBOSE to silence or expand this message)
└ @ CUDAdrv /home/olszewskip/.julia/packages/CUDAdrv/mCr0O/src/CUDAdrv.jl:69


In [27]:
function f(x, dict)
    
end

f (generic function with 1 method)

In [28]:
f(5)

5

In [23]:
dict = Dict{1 => 0.1, 2 => 0.2}

Dict{1 => 0.1,2 => 0.2}

In [24]:
x = [4 5]

1×2 Array{Int64,2}:
 4  5

In [6]:
typeof(Tuple([2, 1]))

Tuple{Int64,Int64}

In [53]:
dict = Dict{Tuple{Int32, Int32}, Float16}()
dict[(1, 1)] = 0.5;
dict[(2, 2)] = 0.2;
dict

Dict{Tuple{Int32,Int32},Float16} with 2 entries:
  (2, 2) => 0.19995
  (1, 1) => 0.5

In [9]:
using SparseArrays

In [30]:
arr = Array(reshape(1:6, 2, 3))

2×3 Array{Int64,2}:
 1  3  5
 2  4  6

In [39]:
collect(zip(keys(dict)...))

2-element Array{Tuple{Int64,Int64},1}:
 (2, 1)
 (2, 1)

In [43]:
collect(dict)

2-element Array{Pair{Tuple{Int64,Int64},Float32},1}:
 (2, 2) => 0.2
 (1, 1) => 0.5

In [52]:
I = Vector{Int32}(undef, length(dict));
J = Vector{Int32}(undef, length(dict));
V = Vector{Float16}(undef, length(dict));

In [55]:
collect(enumerate(dict))

2-element Array{Tuple{Int64,Pair{Tuple{Int32,Int32},Float16}},1}:
 (1, (2, 2) => 0.2)
 (2, (1, 1) => 0.5)

In [61]:
sparse(I, J, V)

2×2 SparseMatrixCSC{Float16,Int32} with 2 stored entries:
  [1, 1]  =  0.5
  [2, 2]  =  0.2

In [20]:
hcat(collect(keys(dict)))

2×1 Array{Tuple{Int64,Int64},2}:
 (1, 2)
 (2, 2)

In [62]:
typeof(dict)

Dict{Tuple{Int32,Int32},Float16}

In [64]:
Vector()

0-element Array{Any,1}

In [11]:
?assert

search: AssertionError @assert typeassert

Couldn't find assert
Perhaps you meant @assert, asec, asecd, asech, Cshort, insert!, isperm or isqrt


No documentation found.

Binding `assert` does not exist.


In [18]:
mutable struct MyNum_
    num
end

In [19]:
my_num_ = MyNum_(4)

MyNum_(4)

In [21]:
my_num_.num

5

In [5]:
struct Dok{T} where {T}
    num::T
    dict::Dict{T}
end
Dok(num) = Dok(num, Dict())

ErrorException: syntax: invalid type signature

In [4]:
Dok(2)

Dok{Any}(2, Dict{Any,Any}())

In [4]:
struct DokLayer{T,S,F} where {T}
    m::T
    n::T
    dict::Dict{Tuple{T, T}, S}
    σ::F
end

DokMatrix(m, n) = DokMatrix(m, n, Dict(), identity)

function update(dok_mat, I, J, V)
    for (i, j, v) in zip(I, J, V)
        @assert i <= dok_mat.m && j <= dok_mat.n
        dok_mat.dict[(i, j)] = v
    end
end

ErrorException: syntax: invalid type signature

In [4]:
dok_matrix = DokMatrix(2, 3)

MethodError: MethodError: no method matching DokMatrix(::Int64, ::Int64, ::Dict{Any,Any}, ::typeof(identity))
Closest candidates are:
  DokMatrix(::Any, ::Any) at In[3]:8

In [23]:
update(dok_matrix, [2], [1], [0.5])

In [24]:
dok_matrix

DokMatrix(2, 3, Dict((2, 1) => 0.5))

---

In [2]:
using Flux

In [9]:
dict = Dict(1=>2)

Dict{Int64,Int64} with 1 entry:
  1 => 2

In [4]:
vect = [10 20]

1×2 Array{Int64,2}:
 10  20

In [4]:
sum(keys(dict))

3

In [7]:
(sum ∘ keys)(dict)

3

In [13]:
?back

search: backtrace catch_backtrace ExponentialBackOff BatchNorm broadcast

Couldn't find back
Perhaps you meant lock, mark, Task, Base, break, big, bind, abs, Main or ans


No documentation found.

Binding `back` does not exist.


In [12]:
gradient(first∘keys, dict)

MethodError: MethodError: no method matching getindex(::Dict{Any,Any})
Closest candidates are:
  getindex(::Dict{K,V}, !Matched::Any) where {K, V} at dict.jl:476
  getindex(::AbstractDict, !Matched::Any) at abstractdict.jl:467
  getindex(::AbstractDict, !Matched::Any, !Matched::Any, !Matched::Any...) at abstractdict.jl:476
  ...

In [32]:
function sum_multiplying(vect, dict)
#     keys = [1]
#     vals = [10]
    sum = 0
    for (key, val) in zip(keys, vals)
        sum += vect[key] * val
    end
    return sum
end

sum_multiplying (generic function with 3 methods)

In [28]:
getfirst(vect) = vect[1]

getfirst (generic function with 1 method)

In [33]:
gradient(sum_multiplying, vect, [1], [10])

([10 0], nothing, [10])

In [13]:
using SparseArrays

In [15]:
sp_arr = sparse([1, 2, 3], [2, 1, 3], [10, 20, 30])

3×3 SparseMatrixCSC{Int64,Int64} with 3 stored entries:
  [2, 1]  =  20
  [1, 2]  =  10
  [3, 3]  =  30

---

In [1]:
using Zygote

In [10]:
dict = Dict(1=>10, 2=>20);
vect = [1, 2]

2-element Array{Int64,1}:
 1
 2

In [13]:
getindex(dict, 1)

10

In [70]:
gradient(dict -> dict[1], Dict(1=>10))

(Dict{Any,Any}(1 => 1),)

In [11]:
using SparseArrays

In [56]:
vec = sparsevec([2], [2], 2)

2-element SparseVector{Int64,Int64} with 1 stored entry:
  [2]  =  2

In [61]:
sparse([1, 2], [1, 2], [10, 20], 3, 2)

3×2 SparseMatrixCSC{Int64,Int64} with 2 stored entries:
  [1, 1]  =  10
  [2, 2]  =  20

In [62]:
gradient(W -> sum(W * vec), sparse([1, 2], [1, 2], [10, 20], 3, 2))

([0 2; 0 2; 0 2],)

In [9]:
gradient(sum, sparse([]))

UndefVarError: UndefVarError: sparse not defined

In [47]:
struct Dict_
    m
    n
    dict
end

#dict_ = Dict_(3, 2, Dict(1 => Set([(2, 10)]), 3 => Set([(1, 30)])))
dict_ = Dict_(3, 2, Dict(1 => 10, 3 => 30))

Dict_(3, 2, Dict(3 => 30,1 => 10))

In [ ]:
function 

In [36]:
get(Dict(0=>1), 0, 0)

1

In [82]:
vect = ['a', 'b']

2-element Array{Char,1}:
 'a'
 'b'

In [83]:
Dict(index => elem for (index, elem) in enumerate(vect))

Dict{Int64,Char} with 2 entries:
  2 => 'b'
  1 => 'a'

In [84]:
vect2dict(vect) = Dict(index => elem for (index, elem) in enumerate(vect))

vect2dict (generic function with 1 method)

In [85]:
mat = 

2×2 Array{Int64,2}:
 1  2
 3  4

In [101]:
zero([1, 2])

2-element Array{Int64,1}:
 0
 0

In [125]:
findnz(sparsevec([1 0]))

([1], [1])

In [135]:
sp_vec = sprand(2, 0.5)
Vector(sp_vec)

2-element Array{Float64,1}:
 0.0               
 0.1551314176788876

In [138]:
sp_vec.nzval

1-element Array{Float64,1}:
 0.1551314176788876

In [129]:
sp_arr = sprand(3, 2, 0.5)
Matrix(sp_arr)

3×2 Array{Float64,2}:
 0.356838  0.0     
 0.0       0.0     
 0.0       0.758888

In [130]:
sp_arr.colptr

3-element Array{Int64,1}:
 1
 2
 3

In [143]:
sp_arr.nzval

2-element Array{Float64,1}:
 0.3568375111919624
 0.7588878466506941

In [144]:
sp_arr.rowval

2-element Array{Int64,1}:
 1
 3

In [149]:
sparsevec(3)

MethodError: MethodError: no method matching sparsevec(::Int64, ::UndefInitializer)

In [150]:
typeof([])

Array{Any,1}

In [164]:
di = Dict(1=>1, 2=>2)

Dict{Int64,Int64} with 2 entries:
  2 => 2
  1 => 1

In [165]:
sum(di[i] * x for (i, x) in enumerate([1, 2]))

5

In [3]:
using Zygote

In [14]:
struct Linear
    W
    b
    dict
end

l = Linear(rand(2, 5), rand(2), Dict(1=>10))
x = rand(5);

function test(l)
    sum_ = sum(l.W * x + l.b)
    for (key, val) in pairs(l.dict)
        sum_ *= val
    end
    return sum_
end

test (generic function with 1 method)

In [17]:
import Base: getfield

In [27]:
import Base: +

In [32]:
union(Dict(1=>10), Dict(1=>20))

2-element Array{Pair{Int64,Int64},1}:
 1 => 10
 1 => 20

In [46]:
?Zygote.accum

No documentation found.

`Zygote.accum` is a `Function`.

```
# 9 methods for generic function "accum":
[1] accum() in Zygote at /home/olszewskip/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:5
[2] accum(x::Tuple, y::Tuple) in Zygote at /home/olszewskip/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:15
[3] accum(x::AbstractArray, y::AbstractArray) in Zygote at /home/olszewskip/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:16
[4] accum(x::NamedTuple, y::NamedTuple) in Zygote at /home/olszewskip/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:19
[5] accum(x::Base.RefValue, y::Base.RefValue) in Zygote at /home/olszewskip/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:24
[6] accum(a::AbstractDict, b::AbstractDict) in Zygote at /home/olszewskip/.julia/packages/Zygote/oPQFy/src/lib/base.jl:30
[7] accum(x) in Zygote at /home/olszewskip/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:6
[8] accum(x, y) in Zygote at /home/olszewskip/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:8
[9] accum(x, y, zs...) in Zygote at /home/olszewskip/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:13
```


In [49]:
gradient(getindex, Dict(1=>10), 1)

KeyError: KeyError: key 1 not found

In [41]:
function +(d1::Dict, d2::Dict)
    sum_ = Dict()
    for d in [d1, d2]
        for (key, val) in d
            if key in keys(sum_)
                sum_[key] += val
            else
                sum_[key] = val
            end
        end
    end
    return sum_
end

+ (generic function with 208 methods)

In [42]:
Dict('a' => 1, 'b' => 2) + Dict('b' => 3, 'c' => 4)

Dict{Any,Any} with 3 entries:
  'a' => 1
  'c' => 4
  'b' => 5

In [20]:
@adjoint getfield(object, field) = getfield(object, field),

Dict{Int64,Int64} with 1 entry:
  1 => 10

In [25]:
gradient(sum∘values∘getfield, l, :dict)

MethodError: MethodError: no method matching getindex(::Dict{Any,Any})
Closest candidates are:
  getindex(::Dict{K,V}, !Matched::Any) where {K, V} at dict.jl:476
  getindex(::AbstractDict, !Matched::Any) at abstractdict.jl:467
  getindex(::AbstractDict, !Matched::Any, !Matched::Any, !Matched::Any...) at abstractdict.jl:476

In [15]:
grads = gradient(test, l)[1]

ErrorException: Non-differentiable function getfield

In [68]:
grads[:b]

2-element FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}:
 1.0
 1.0

In [40]:
struct Test
    m
    n
    weights
end

function (t::Test)(x)
    out = Zygote.Buffer(x, t.m)
    for i in 1:t.m
        out[i] = 0
    end
    for ((i, j), w) in t.weights
        out[i] += w * x[j]
    end
    return copy(out)
end

In [41]:
te = Test(3, 2, Dict((1, 1) => 10, (3, 2) => 20))

Test(3, 2, Dict((3, 2) => 20,(1, 1) => 10))

In [42]:
te([1 2])

3-element Array{Int64,1}:
 10
  0
 40

In [57]:
getfield(te, :m)

3

In [ ]:
gradient(getfield)

In [43]:
dmodel = gradient(model -> sum(model([1 2])), te)

ErrorException: Non-differentiable function getfield

In [49]:
struct Layer
    I
    J
    V
end

In [52]:
1 in ([1])

true

In [55]:
gradient(x -> x in keys(Dict(1=>10)), 2)

(nothing,)

In [46]:
layer = Layer([1 2], [1 2], [])
vectL = [1 2]
vectR = [3 4]
function test(layer)
    sum = 0
    for (i, j, v) in zip(layer.I, layer.J, layer.V)
        sum += vectL[i] * vectR[j] * v
    end
    return sum
end

test (generic function with 1 method)

In [47]:
test(dict)

80

In [48]:
gradient(test, dict)

ErrorException: Non-differentiable function getfield

In [142]:
gradient(test, findnz(sp_vec)..., findnz(sp_arr)...)

ErrorException: Need an adjoint for constructor SparseMatrixCSC{Float64,Int64}. Gradient is of type Array{Float64,2}

In [113]:
dict = Dict(1=>10)
function test(vect)
    sum = 0
    for (key, val) in dict
        sum += val * vect[key]
    end
    return sum
end

test (generic function with 2 methods)

In [141]:
function test(arr_I, arr_J_ptr, arr_V, vec_J, vec_V)
    out_vec = Dict()
    out_vec_V = []
    for vec_j, vec_v in zip(vec_K, vec_V)
        for i in arr_J_ptr[vec_j] : (arr_J_ptr[vec_j + 1] - 1)
            arr_i = arr_I[i]
            arr_val = arr_V[i]
            
    return sum(W * x)
end

test (generic function with 4 methods)

In [114]:
gradient(test, [10 20])

ErrorException: Non-differentiable function getfield

In [97]:
pullback(sum∘values∘dict_id, Dict(1=>10))[2](1)

MethodError: MethodError: no method matching getindex(::Dict{Any,Any})
Closest candidates are:
  getindex(::Dict{K,V}, !Matched::Any) where {K, V} at dict.jl:476
  getindex(::AbstractDict, !Matched::Any) at abstractdict.jl:467
  getindex(::AbstractDict, !Matched::Any, !Matched::Any, !Matched::Any...) at abstractdict.jl:476

In [81]:
gradient(vect2dict, [1 2], Dict('a' => 1), 'a')

([1 0], nothing, nothing)

In [2]:
struct COO_mat
    I::Set{Integer}
    J::Vector{Integer}
    IV::Vector{Pair{Integer, Float32}}
end

In [60]:
function test(input, layer)
    output = Dict()
    for (j, x_j) in zip(input.I, input.V)
        for (j_, IV_pair) in zip(layer.J, layer.IV)
            
        if j in keys(layer)
            column = layer[j]
            for (i, weight_ij) in column
                output[i] = weight_ij * x_j
            end
        end
    end
    return (sum∘values)(output)
end

test (generic function with 1 method)

In [61]:
test(Dict(1=>1, 2=>2), Dict(1=>Dict(1=>10), 2=>Dict(2=>20)))

50

In [62]:
gradient(test, Dict(1=>1, 2=>2), Dict(1=>Dict(1=>10), 2=>Dict(2=>20)))

UndefRefError: UndefRefError: access to undefined reference

In [62]:
function test(dict)
    sum = 0
    for key in keys(dict)
        sum += dict[key]
    end
    return sum
end    

test (generic function with 1 method)

In [63]:
gradient(test, Dict(1=>10))

(Dict{Any,Any}(1 => 1),)

---
---

In [2]:
using Pkg

In [4]:
Pkg.installed()["Flux"]

v"0.10.1"

In [3]:
using Flux

┌ Info: CUDAdrv.jl failed to initialize, GPU functionality unavailable (set JULIA_CUDA_SILENT or JULIA_CUDA_VERBOSE to silence or expand this message)
└ @ CUDAdrv /home/olszewskip/.julia/packages/CUDAdrv/mCr0O/src/CUDAdrv.jl:69


In [4]:
struct Layer
  dict
end

(l::Layer)(x) = l.dict[0] .* x 

Flux.@functor Layer

model = Layer(Dict(0 => 1))

x = [1 2]
y = [2 3]

gs = gradient(model -> sum(model(x) .* y), model)

((dict = Dict{Any,Any}(0 => 8),),)

In [9]:
nfields(model)

1

In [11]:
getfield(model, 1)

Dict{Int64,Int64} with 1 entry:
  0 => 1

In [1]:
using Flux
using Zygote

struct SparseFF{T,S,F}
    m::T
    n::T
    dict::AbstractDict{Tuple{T,T},S}
    σ::F
end

function Base.show(io::IO, layer::SparseFF)
  print(io, "SparseFF(", layer.n, ", ", layer.m)
  print(io, ", ", round(length(layer.dict) / (layer.m * layer.n), sigdigits=5))
  layer.σ == identity || print(io, ", ", layer.σ)
  print(io, ")")
end

function SparseFF(in::T, out::T, sparsity::Number, σ::Function) where {T<:Unsigned}
    dict = Dict{Tuple{T,T}, Float32}()
    for i in 1:out, j in 1:in
        if rand() < sparsity
            dict[(i, j)] = randn(Float32)
        end
    end
    return SparseFF(out, in, dict, σ)
end

SparseFF(in, out, sparsity) = SparseFF(in, out, sparsity, identity)

function (layer::SparseFF)(x)
    out = Zygote.Buffer(x, layer.m)
    for i in 1:layer.m
        out[i] = 0
    end
    for (i, j) in keys(layer.dict)
        out[i] += layer.dict[(i, j)] * x[j]
    end
    return layer.σ.(copy(out))
end

# Flux.@functor SparseFF

┌ Info: CUDAdrv.jl failed to initialize, GPU functionality unavailable (set JULIA_CUDA_SILENT or JULIA_CUDA_VERBOSE to silence or expand this message)
└ @ CUDAdrv /home/olszewskip/.julia/packages/CUDAdrv/mCr0O/src/CUDAdrv.jl:69


In [2]:
model = Flux.Chain(
    SparseFF(UInt16(30), UInt16(20), 0.1, σ),
    SparseFF(UInt16(20), UInt16(10), 0.1, σ),
    Flux.Dense(10, 5),
    Flux.softmax
)

Chain(SparseFF(30, 20, 0.11, σ), SparseFF(20, 10, 0.11, σ), Dense(10, 5), softmax)

In [3]:
loss(model, x, y) = Flux.crossentropy(model(x), y)

loss (generic function with 1 method)

In [4]:
x = Vector(rand(Float32, 30));
y = Vector(rand(Float32, 5));

In [ ]:
grads_ = gradient(model)

In [17]:
grads = gradient(model -> loss(model, x, y), model)

((layers = ((m = nothing, n = nothing, dict = Dict{Any,Any}((0x0008, 0x001d) => 0.0f0,(0x0011, 0x000f) => 0.0033891234f0,(0x000e, 0x000a) => 0.00924852f0,(0x000a, 0x0005) => 5.9139194f-5,(0x000b, 0x0001) => 0.0f0,(0x000f, 0x0012) => -0.00038765688f0,(0x0008, 0x0012) => 0.0f0,(0x000c, 0x0007) => 0.0038793471f0,(0x0014, 0x0016) => 0.00029475515f0,(0x0007, 0x001c) => 0.0f0…), σ = nothing), (m = nothing, n = nothing, dict = Dict{Any,Any}((0x0005, 0x0011) => -0.076646015f0,(0x0008, 0x0002) => 0.0024109164f0,(0x0006, 0x0009) => 0.13765791f0,(0x0004, 0x000c) => 0.035799365f0,(0x0008, 0x000c) => 0.002123489f0,(0x0009, 0x0014) => 0.0035257752f0,(0x0002, 0x000c) => 0.005353766f0,(0x0009, 0x0004) => 0.004779541f0,(0x0009, 0x000f) => 0.0034835131f0,(0x0004, 0x0014) => 0.026821904f0…), σ = nothing), (W = Float32[-0.067485824 -0.105230816 … -0.00816829 -0.08510358; -0.32730767 -0.5103717 … -0.03961638 -0.41275415; … ; -0.08757552 -0.13655671 … -0.010599889 -0.110437855; 0.16874668 0.26312712 … 0.020

In [14]:
model[3]

Dense(10, 5)

In [15]:
grads[3]

BoundsError: BoundsError: attempt to access ((layers = ((m = nothing, n = nothing, dict = Dict{Any,Any}((0x0008, 0x001d) => 0.0f0,(0x0011, 0x000f) => 0.0033891234f0,(0x000e, 0x000a) => 0.00924852f0,(0x000a, 0x0005) => 5.9139194f-5,(0x000b, 0x0001) => 0.0f0,(0x000f, 0x0012) => -0.00038765688f0,(0x0008, 0x0012) => 0.0f0,(0x000c, 0x0007) => 0.0038793471f0,(0x0014, 0x0016) => 0.00029475515f0,(0x0007, 0x001c) => 0.0f0,(0x000d, 0x0007) => 0.0f0,(0x0009, 0x0016) => -0.0004435256f0,(0x0004, 0x0009) => -0.00018296354f0,(0x0013, 0x001c) => 0.0f0,(0x0013, 0x0014) => 0.0f0,(0x0010, 0x001e) => 0.0f0,(0x000e, 0x0002) => 0.009866612f0,(0x0006, 0x000b) => 0.0f0,(0x000c, 0x000e) => 0.0033979472f0,(0x0010, 0x001b) => 0.0f0,(0x0002, 0x001b) => -0.0024889172f0,(0x0008, 0x0015) => 0.0f0,(0x0005, 0x0014) => 0.0f0,(0x000d, 0x000e) => 0.0f0,(0x0001, 0x0014) => -0.002279399f0,(0x0014, 0x001c) => 0.001388255f0,(0x0003, 0x0010) => 0.030094286f0,(0x0005, 0x0009) => 0.0f0,(0x0005, 0x000a) => 0.0f0,(0x0001, 0x0004) => -0.0016561262f0,(0x0005, 0x0008) => 0.0f0,(0x0013, 0x0006) => 0.0f0,(0x0012, 0x000c) => 0.0f0,(0x000e, 0x0016) => 0.0021953888f0,(0x0004, 0x001c) => -0.000932651f0,(0x0008, 0x001e) => 0.0f0,(0x000a, 0x0008) => 5.4805845f-5,(0x0004, 0x0013) => -0.00027438844f0,(0x0002, 0x0016) => -0.00064986903f0,(0x0006, 0x000c) => 0.0f0,(0x000d, 0x0005) => 0.0f0,(0x0006, 0x0003) => 0.0f0,(0x0001, 0x0007) => -0.0019396663f0,(0x0008, 0x0008) => 0.0f0,(0x0004, 0x000f) => -0.0007130933f0,(0x000f, 0x0010) => -0.00073845487f0,(0x0009, 0x0018) => -0.0012303584f0,(0x000f, 0x000e) => -0.0008120032f0,(0x0010, 0x000a) => 0.0f0,(0x0004, 0x0001) => -0.00028362294f0,(0x0009, 0x0007) => -0.0018216338f0,(0x0012, 0x000f) => 0.0f0,(0x0002, 0x001e) => -0.0028175272f0,(0x0005, 0x0006) => 0.0f0,(0x0004, 0x000e) => -0.00071237993f0,(0x0013, 0x0015) => 0.0f0,(0x0002, 0x000a) => -0.002737705f0,(0x000e, 0x0010) => 0.0071825394f0,(0x000e, 0x0009) => 0.002028452f0,(0x0006, 0x001c) => 0.0f0,(0x0009, 0x000f) => -0.0015971796f0,(0x0004, 0x0014) => -0.00095575594f0,(0x0003, 0x0011) => 0.016735032f0,(0x000a, 0x0012) => 2.0376383f-5,(0x000c, 0x000c) => 0.0010701467f0,(0x0009, 0x000b) => -0.0019975766f0), σ = nothing), (m = nothing, n = nothing, dict = Dict{Any,Any}((0x0005, 0x0011) => -0.076646015f0,(0x0008, 0x0002) => 0.0024109164f0,(0x0006, 0x0009) => 0.13765791f0,(0x0004, 0x000c) => 0.035799365f0,(0x0008, 0x000c) => 0.002123489f0,(0x0009, 0x0014) => 0.0035257752f0,(0x0002, 0x000c) => 0.005353766f0,(0x0009, 0x0004) => 0.004779541f0,(0x0009, 0x000f) => 0.0034835131f0,(0x0004, 0x0014) => 0.026821904f0,(0x0003, 0x0002) => 0.0073519014f0,(0x0006, 0x0011) => 0.10935148f0,(0x0003, 0x000e) => 0.0069469535f0,(0x0003, 0x000c) => 0.006475414f0,(0x0001, 0x0001) => -0.016037386f0,(0x0008, 0x0004) => 0.0021567305f0,(0x0009, 0x0002) => 0.005342844f0,(0x000a, 0x0003) => 0.107073225f0,(0x0006, 0x000e) => 0.16382308f0,(0x0003, 0x0014) => 0.0048515643f0,(0x000a, 0x0002) => 0.15172808f0,(0x0008, 0x000a) => 0.0026080012f0), σ = nothing), (W = Float32[-0.067485824 -0.105230816 -0.045420498 -0.077783 -0.06785592 -0.07932278 -0.06623152 -0.12773262 -0.00816829 -0.08510358; -0.32730767 -0.5103717 -0.22029038 -0.3772492 -0.3291026 -0.38471714 -0.32122427 -0.6195059 -0.03961638 -0.41275415; 0.31362233 0.4890321 0.21107963 0.36147574 0.31534222 0.36863142 0.3077933 0.5936032 0.037959944 0.39549613; -0.08757552 -0.13655671 -0.058941618 -0.10093804 -0.088055775 -0.10293618 -0.08594782 -0.16575703 -0.010599889 -0.110437855; 0.16874668 0.26312712 0.11357287 0.19449455 0.16967209 0.19834471 0.16561033 0.31939235 0.020424614 0.21279946], b = Float32[-0.13246304, -0.64244854, 0.6155866, -0.17189564, 0.33122066], σ = nothing), nothing),),)
  at index [3]

In [8]:
getfield(grads, 1)

(layers = ((m = nothing, n = nothing, dict = Dict{Any,Any}((0x0008, 0x001d) => 0.0f0,(0x0011, 0x000f) => 0.0033891234f0,(0x000e, 0x000a) => 0.00924852f0,(0x000a, 0x0005) => 5.9139194f-5,(0x000b, 0x0001) => 0.0f0,(0x000f, 0x0012) => -0.00038765688f0,(0x0008, 0x0012) => 0.0f0,(0x000c, 0x0007) => 0.0038793471f0,(0x0014, 0x0016) => 0.00029475515f0,(0x0007, 0x001c) => 0.0f0…), σ = nothing), (m = nothing, n = nothing, dict = Dict{Any,Any}((0x0005, 0x0011) => -0.076646015f0,(0x0008, 0x0002) => 0.0024109164f0,(0x0006, 0x0009) => 0.13765791f0,(0x0004, 0x000c) => 0.035799365f0,(0x0008, 0x000c) => 0.002123489f0,(0x0009, 0x0014) => 0.0035257752f0,(0x0002, 0x000c) => 0.005353766f0,(0x0009, 0x0004) => 0.004779541f0,(0x0009, 0x000f) => 0.0034835131f0,(0x0004, 0x0014) => 0.026821904f0…), σ = nothing), (W = Float32[-0.067485824 -0.105230816 … -0.00816829 -0.08510358; -0.32730767 -0.5103717 … -0.03961638 -0.41275415; … ; -0.08757552 -0.13655671 … -0.010599889 -0.110437855; 0.16874668 0.26312712 … 0.0204

In [35]:
ps = Flux.params(model[1])

Params([])

In [27]:
gs = gradient(ps) do
    loss(model, x, y)
end

Grads(...)

In [25]:
typeof(params(model[3]))

Params

In [34]:
gs.grads

IdDict{Any,Any} with 6 entries:
  Buffer{Float32,Array{Flo… => Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, …
  Dict((0x0003, 0x0006)=>1… => Dict{Any,Any}((0x0008, 0x0017)=>-9.86251e-5,(0x0…
  Buffer{Float32,Array{Flo… => Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, …
  Float32[-0.0122392, 0.01… => Float32[0.0122392, -0.0191127, -0.0394179, 0.025…
  Float32[-0.536194 -0.391… => Float32[0.00941797 0.00434556 … 0.00871493 0.006…
  Dict((0x0007, 0x0002)=>1… => Dict{Any,Any}((0x0007, 0x0002)=>0.0125634,(0x000…

In [30]:
Flux.Optimise.update!(Flux.Descent(), params(model[2]), gs)

In [68]:
length(model)

4

In [58]:
typeof(model.layers[1])

SparseFF{UInt16,Float32,typeof(σ)}

In [57]:
gs.layers[1].dict

Dict{Any,Any} with 66 entries:
  (0x000f, 0x0011) => 0.197872
  (0x000a, 0x000b) => 0.0
  (0x0001, 0x000f) => 0.375903
  (0x0014, 0x0005) => 0.000765467
  (0x0001, 0x000c) => 0.387952
  (0x0012, 0x0015) => -0.175319
  (0x0009, 0x001c) => 0.0
  (0x0003, 0x0012) => 0.0
  (0x000b, 0x0017) => 0.0
  (0x000e, 0x0002) => 0.556112
  (0x0005, 0x0011) => -0.0791344
  (0x0010, 0x001c) => 0.0
  (0x0001, 0x0012) => 0.577095
  (0x0008, 0x0018) => 0.0
  (0x0003, 0x0009) => 0.0
  (0x0013, 0x0013) => 0.00996453
  (0x0012, 0x0013) => -0.0519935
  (0x000b, 0x0014) => 0.0
  (0x000c, 0x001a) => -0.00200821
  (0x0005, 0x0013) => -0.0207084
  (0x0012, 0x000c) => -0.189229
  (0x000f, 0x0001) => 0.267078
  (0x0007, 0x001b) => 0.168457
  (0x000e, 0x0016) => 0.436812
  (0x000e, 0x0012) => 0.685089
  ⋮                => ⋮

In [53]:
for (param, grad) in zip(model.layers[1], gs.layers[1])
    println(param, grad)
end

MethodError: MethodError: no method matching iterate(::SparseFF{UInt16,Float32,typeof(σ)})
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:600
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:600
  iterate(!Matched::ExponentialBackOff) at error.jl:218
  ...

In [40]:
gs[model[2]].dict

ErrorException: type Nothing has no field dict

In [17]:
[gs[p] for p in ps]

ErrorException: Only reference types can be differentiated with `Params`.

In [15]:
for p in ps
    println(gs[p])
end

nothing
nothing


ErrorException: Only reference types can be differentiated with `Params`.

In [6]:
y = Vector(sprand(Float32, 10, 1.))

10-element Array{Float32,1}:
 0.9786658   
 0.568933    
 0.804896    
 0.5060786   
 0.0053601265
 0.32529593  
 0.941293    
 0.95486486  
 0.052418232 
 0.99728906  

In [7]:
x = Vector(sprand(Float32, 30, 1.))

30-element Array{Float32,1}:
 0.99993074
 0.30630112
 0.7602762 
 0.25079393
 0.978377  
 0.40243483
 0.72626233
 0.7394893 
 0.27526045
 0.8950535 
 0.23692632
 0.22312045
 0.17353046
 ⋮         
 0.8915237 
 0.7626835 
 0.57289577
 0.7487407 
 0.7178049 
 0.26677704
 0.24272895
 0.6672803 
 0.5442846 
 0.70706594
 0.49650443
 0.41240144

In [23]:
grads = gradient(model -> loss(model(x), y), model)[1];

In [26]:
typeof(grads)

NamedTuple{(:layers,),Tuple{Tuple{NamedTuple{(:m, :n, :dict, :σ),Tuple{Nothing,Nothing,Dict{Any,Any},Nothing}},NamedTuple{(:m, :n, :dict, :σ),Tuple{Nothing,Nothing,Dict{Any,Any},Nothing}},Nothing}}}

In [25]:
for param in Params(model)
    println(grads[param])
end

MethodError: MethodError: no method matching getindex(::NamedTuple{(:layers,),Tuple{Tuple{NamedTuple{(:m, :n, :dict, :σ),Tuple{Nothing,Nothing,Dict{Any,Any},Nothing}},NamedTuple{(:m, :n, :dict, :σ),Tuple{Nothing,Nothing,Dict{Any,Any},Nothing}},Nothing}}}, ::SparseFF{UInt16,Float32,typeof(σ)})
Closest candidates are:
  getindex(::NamedTuple, !Matched::Int64) at namedtuple.jl:106
  getindex(::NamedTuple, !Matched::Symbol) at namedtuple.jl:107
  getindex(::Any, !Matched::AbstractTrees.ImplicitRootState) at /home/olszewskip/.julia/packages/AbstractTrees/z1wBY/src/AbstractTrees.jl:344

In [10]:
typeof(grads.layers[1])

NamedTuple{(:m, :n, :dict, :σ),Tuple{Nothing,Nothing,Dict{Any,Any},Nothing}}

In [11]:
typeof(model.layers[1])

SparseFF{UInt16,Float32,typeof(σ)}

In [12]:
function update!(opt::Descent, layer::SparseFF, grad)
    merge!((x -> opt.eta * x)∘+, layer.dict,  grad[:dict])
end

update! (generic function with 1 method)

In [ ]:
update!(Flux.Descent(), )

In [107]:
Flux.train!(Flux.crossentropy, Flux.params(model), [(x,y)], Flux.Descent())

DimensionMismatch: DimensionMismatch("arrays could not be broadcast to a common size; got a dimension with lengths 10 and 30")

In [97]:
model.layers[1].dict

Dict{Tuple{UInt16,UInt16},Float32} with 56 entries:
  (0x0001, 0x0017) => -1.91749
  (0x000f, 0x001d) => 1.41232
  (0x0002, 0x0012) => 1.23592
  (0x000c, 0x0010) => 1.46087
  (0x000f, 0x0012) => 0.179804
  (0x0003, 0x0001) => 1.06565
  (0x000f, 0x001c) => -0.809944
  (0x0010, 0x000d) => 0.118007
  (0x0001, 0x000a) => -0.314179
  (0x000f, 0x000f) => 0.243218
  (0x0010, 0x0003) => -0.406935
  (0x0014, 0x000d) => 1.53791
  (0x0009, 0x0002) => -0.337235
  (0x0002, 0x000d) => 0.0403535
  (0x0002, 0x001b) => 0.29069
  (0x0013, 0x0018) => -2.20206
  (0x000a, 0x000c) => -1.14364
  (0x0014, 0x0006) => 1.29082
  (0x0003, 0x0010) => -0.639161
  (0x0009, 0x0011) => 0.472778
  (0x000b, 0x001b) => 0.691826
  (0x000a, 0x001a) => 0.425954
  (0x0008, 0x0011) => 0.435237
  (0x0012, 0x001d) => 1.25348
  (0x000e, 0x0006) => 0.818237
  ⋮                => ⋮

In [54]:
grads[:layers][1][:dict]

Dict{Any,Any} with 56 entries:
  (0x0001, 0x0017) => -0.00344454
  (0x000f, 0x001d) => 0.0355532
  (0x0002, 0x0012) => 0.0421302
  (0x000c, 0x0010) => 0.0
  (0x000f, 0x001c) => 0.0160266
  (0x0003, 0x0001) => 0.0
  (0x0010, 0x000d) => 0.0
  (0x000f, 0x0012) => 0.0779121
  (0x000f, 0x000f) => 0.0794192
  (0x0001, 0x000a) => -0.000534103
  (0x0010, 0x0003) => 0.0
  (0x0014, 0x000d) => 0.00135714
  (0x0009, 0x0002) => -0.0985117
  (0x0002, 0x000d) => 0.00697144
  (0x0002, 0x001b) => 0.0325018
  (0x0013, 0x0018) => 0.0
  (0x0014, 0x0006) => 0.00670294
  (0x000a, 0x000c) => 0.0357397
  (0x0003, 0x0010) => 0.0
  (0x0009, 0x0011) => -0.10278
  (0x000b, 0x001b) => -0.000791557
  (0x000a, 0x001a) => 0.0512622
  (0x0008, 0x0011) => 0.0
  (0x0012, 0x001d) => -0.00444119
  (0x000e, 0x0006) => 0.0
  ⋮                => ⋮

In [ ]:
grads = gradient(layer -> (loss∘test)(layer, [1 2]), layer)[1]

In [3]:
function test(dok, vect)
    out = Zygote.Buffer(vect, dok.m)
    for i in 1:dok.m
        out[i] = 0
    end
    for (i, j) in keys(dok.dict)
        out[i] += dok.dict[(i, j)] * vect[j]
    end
    return copy(out)
end

test (generic function with 1 method)

In [4]:
test(layer, [1. 2.])

3-element Array{Float64,1}:
 10.0
  0.0
  0.0

In [5]:
(sum∘test)(layer, [1 2])

10

In [10]:
grads = gradient(layer -> (sum∘test)(layer, [1 2]), layer)[1]

(m = nothing, n = nothing, dict = Dict{Any,Any}((1, 1) => 1.0))

In [7]:
η = 0.1

0.1

In [8]:
grads[:dict]

Dict{Any,Any} with 1 entry:
  (1, 1) => 1.0

In [162]:
merge!((x -> η * x)∘+, layer.dict,  grads[:dict])

Dict{Tuple{Int64,Int64},Float64} with 1 entry:
  (1, 1) => 0.22

In [158]:
layer

DOKSparse(3, 2, Dict((1, 1) => 11.0))